# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    groups:
      pytest:
        patterns:
          - "pytest*"
          - "aioresponses"
      core:
        patterns:
          - "aiohttp"
          - "discord.py"
          - "jishaku"
          - "orjson"
          - "uvloop"
      asyncpg:
        patterns:
          - "asyncpg*"
      formatting:
        patterns:
          - "ruff"
          - "pre-commit"
        update-types:
          - "major"
          - "minor"
      typing:
        patterns:
          - "pyright"
          - "typing-extensions"
      utils:
        patterns:
          - "toml"
          - "urlextract"
          - "validators"
          - "Pillow"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every monday
      interval: "monthly"
    groups:
      rust:
        patterns:
          - "PyO3/maturin-action"
          - "actions-rs/toolchain"
      python:
        patterns:
          - "jakebailey/pyright-action"
          - "harmon758/postgresql-action"
      artifacts:
        patterns:
          - "actions/upload-artifact"
          - "actions/download-artifact"
  - package-ecosystem: "cargo"
    directory: "charbot_rust"
    schedule:
      # Check for updates to Rust dependencies every weekday
      interval: "weekly"
    groups:
      images:
        patterns:
          - "image"
          - "imageproc"
# GH Pages branch
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/" # Location of package manifests
    target-branch: "gh-pages"
    schedule:
      interval: "monthly"
    groups:
      pages:
        patterns: ["*"]
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "gh-pages"
    schedule:
      # Check for updates to GitHub Actions every monday
      interval: "monthly"
    groups:
      pages:
        patterns: ["*"]
  - package-ecosystem: "bundler"
    directory: "/"
    target-branch: "gh-pages"
    schedule:
      # Check for updates to GitHub Actions every monday
      interval: "monthly"
    groups:
      pages:
        patterns: ["*"]
