# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-json
    -   id: check-toml
    -   id: detect-private-key
    -   id: requirements-txt-fixer
    # -   id: fix-encoding-pragma

-   repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.6.2
    hooks:
    -   id: ruff # Run the linter.
        args: ['--fix']
    -   id: ruff-format # Run the formatter.
