# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-json
    -   id: check-toml
    -   id: fix-encoding-pragma
    -   id: requirements-txt-fixer

-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black
        args:
            - --line-length=120
            - --safe

-   repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
        args:
            - --max-line-length=120
            - --indent-size=4
            - --exclude=backup

-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
    - id: bandit
      args:
          - -s=B101,B311
