codecov:
  require_ci_to_pass: true
  notify:
    wait_for_ci: false
    after_n_builds: 2
ignore:
  - "**/lib.rs"

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        informational: false
        threshold: 2%
        if_ci_failed: error
    patch:
      default:
        informational: false
        threshold: 2%
        if_ci_failed: error

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: true
