# SPDX-FileCopyrightText: 2022 Bluesy1 <68259537+Bluesy1@users.noreply.github.com>
#
# SPDX-License-Identifier: MIT

codecov:
  require_ci_to_pass: true
  notify:
    wait_for_ci: false
    after_n_builds: 2
ignore:
  - "**/lib.rs"

flags:
  python-unit:
    carryforward: true
  rust-unit:
    carryforward: true

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        informational: false
        threshold: 3%
        if_ci_failed: success
    patch:
      default:
        informational: false
        threshold: 3%
        if_ci_failed: success

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: true
