# SPDX-FileCopyrightText: 2022 Bluesy1 <68259537+Bluesy1@users.noreply.github.com>
#
# SPDX-License-Identifier: MIT

codecov:
  require_ci_to_pass: true
  notify:
    wait_for_ci: false
ignore:
  - "**/lib.rs"

flags:
  rust-unit:
    carryforward: true

coverage:
  precision: 2
  round: down
  range: "70...80"
  status:
    project:
      default:
        informational: true
        threshold: 3%
        if_ci_failed: success
    patch:
      default:
        informational: true
        threshold: 3%
        if_ci_failed: success

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no
