# SPDX-FileCopyrightText: 2022 Bluesy1 <68259537+Bluesy1@users.noreply.github.com>
#
# SPDX-License-Identifier: MIT

files:
  - source: /charbot_rust/src/fluent/i18n/en-US/*.ftl
    translation: /charbot_rust/src/fluent/i18n/%locale%/%original_file_name%
