# SPDX-FileCopyrightText: 2022 Bluesy1 <68259537+Bluesy1@users.noreply.github.com>
#
# SPDX-License-Identifier: MIT

[package]
name = "charbot_rust"
version = "1.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "charbot_rust"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.17.3" }
rand = "0.8.5"
image = "0.24.4"
imageproc = "0.23.0"
fluent = { git = "https://github.com/projectfluent/fluent-rs", rev = "8fc76783960217b2a852b9c129ef546b6b8d8bfe", version="0.16.0" }
encoding = "0.2.33"

[dev-dependencies]
yare = "1.0.2"

[features]
extension-module = ["pyo3/extension-module"]
default = ["extension-module"]
