name: CI

on:
  push:
    branches:
      - main
    paths:
    - 'charbot/**'
    - 'tests/**'
    - 'src/**'
    - 'Cargo.*'
    - 'pyproject.toml'
    - '.github/workflows/ci.yml'
  pull_request:
    types: [ opened, reopened, synchronize ]
    paths:
    - 'charbot/**'
    - 'tests/**'
    - 'src/**'
    - 'Cargo.*'
    - 'pyproject.toml'
    - '.github/workflows/ci.yml'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.13"
      - name: Dependencies
        run: |
          pip install ruff -c ruff-requirements.txt
      - name: Run Ruff Check
        env:
          RUFF_OUTPUT_FORMAT: github
        run: ruff check .
      - name: Run Ruff Format
        if: ${{ success() || failure()}}
        run: ruff format --check .
  python-tests:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.13", "3.14" ]
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: ikalnytskyi/action-setup-postgres@c4dda34aae1c821e3a771b68b73b13af3198a7ee # v8
        with:
          postgres-version: '18'
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
          cache-dependency-path: pyproject.toml
      - name: Install
        run: pip install -e ".[dev]"
      - name: Run pytest
        id: pytest
        run: pytest
      - name: Run Pyright
        if: ${{ success() || failure() }}
        uses: jakebailey/pyright-action@8ec14b5cfe41f26e5f41686a31eb6012758217ef # v3.0.2
        with:
          warnings: false
          annotate: ${{ matrix.python-version != '3.13' && 'none' || 'all' }}
          version: 1.1.400 # Optional
