on:
  push:
    branches:
      - main
    paths:
    - 'src/**'
    - 'Cargo.*'
    - '.github/workflows/clippy.yml'
  pull_request:
    types: [ opened, reopened, synchronize ]
    paths:
    - 'src/**'
    - 'Cargo.*'
    - '.github/workflows/clippy.yml'
name: Clippy check

# Make sure CI fails on all warnings, including Clippy lints
env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install stable toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
      - name: Run Clippy
        run: |
          cargo clippy --all-targets --all-features
