on:
  push:
    branches:
      - main
    paths:
    - 'charbot_rust/**'
    - '.github/workflows/clippy.yml'
  pull_request:
    types: [ opened, reopened, synchronize ]
    paths:
    - 'charbot_rust/**'
    - '.github/workflows/clippy.yml'
name: Clippy check

# Make sure CI fails on all warnings, including Clippy lints
env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            charbot_rust/target/
          key: clippy-${{ hashFiles('**/Cargo.lock') }}
      - name: Run Clippy
        run: |
          cd charbot_rust
          cargo clippy --all-targets --all-features
