name: Code Coverage

on:
  push:
    branches:
      - main
  pull_request:
    types: [ opened, reopened, synchronize ]

jobs:
    codecov:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-python@v4
          with:
            python-version: "3.10"
        - name: Install Poetry Action
          uses: snok/install-poetry@v1.3.1
        - name: Load cached $HOME/.local
          uses: actions/cache@v2.1.6
          with:
            path: ~/.local
            key: dotlocal-${{ runner.os }}-${{ hashFiles('.github/workflows/codecov.yml') }}
        - name: Dependencies
          run: poetry install
        - name: Run pytest
          id: pytest
          run: poetry run pytest --cov-report=xml:coverage/reports/coverage.xml --cov=charbot tests/ --cov-report=term
        - name: Upload coverage report
          uses: codecov/codecov-action@v2
          with:
            directory: ./coverage/reports/
            env_vars: OS,PYTHON
            fail_ci_if_error: false
            flags: unittests
            name: codecov-umbrella
            path_to_write_report: ./coverage/codecov_report.txt
            verbose: true
        - name: Report test coverage to DeepSource
          uses: deepsourcelabs/test-coverage-action@master
          with:
            key: python
            coverage-file: ./coverage/reports/coverage.xml
            dsn: ${{ secrets.DEEPSOURCE_DSN }}
