name: Code Coverage

on:
  push:
    branches:
      - main
  pull_request:
    types: [ opened, reopened, synchronize ]

jobs:
    codecov:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-python@v4
          with:
            python-version: "3.10"
            cache: "pip"
            cache-dependency-path: |
              requirements.txt
              requirements-dev.txt
        - name: Dependencies
          run: |
              pip install -U pip
              pip install -Ur requirements.txt -Ur requirements-dev.txt
              pip install -e .
        - name: Run pytest
          id: pytest
          run: pytest --cov-report=xml:coverage/reports/coverage.xml --cov=charbot tests/ --cov-report=term --cov-config=pyproject.toml
        - name: Upload coverage report
          uses: codecov/codecov-action@v2
          with:
            directory: ./coverage/reports/
            env_vars: OS,PYTHON
            fail_ci_if_error: false
            flags: unittests
            name: codecov-umbrella
            path_to_write_report: ./coverage/codecov_report.txt
            verbose: false
        - name: Report test coverage to DeepSource
          uses: deepsourcelabs/test-coverage-action@master
          with:
            key: python
            coverage-file: ./coverage/reports/coverage.xml
            dsn: ${{ secrets.DEEPSOURCE_DSN }}
