name: Code Coverage

on:
  push:
  pull_request:
    types: [ opened, reopened, synchronize ]

jobs:
    codecov:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-python@v3
          with:
            python-version: "3.10"
            cache: "pip"
            cache-dependency-path: |
              requirements.txt
              requirements-dev.txt
        - name: Dependencies
          run: |
              pip install -U pip
              pip install -U -r requirements.txt
              pip install pytest pytest-cov pytest-asyncio
        - name: Run pytest
          id: pytest
          run: pytest --cov-report=xml:coverage/reports/coverage.xml --cov=charbot tests/ --cov-report=term
        - name: Upload coverage report
          uses: codecov/codecov-action@v2
          with:
            directory: ./coverage/reports/
            env_vars: OS,PYTHON
            fail_ci_if_error: true
            flags: unittests
            name: codecov-umbrella
            path_to_write_report: ./coverage/codecov_report.txt
            verbose: true
