name: Leaderboard Pull
on:
  push:
    paths-ignore:
      - '**/_data/users.json**'
  workflow_dispatch:


jobs:
  download-users:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
          cache: "pip"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U -r requirements.txt
      - name: Run sql script
        env:
          DB: ${{ secrets.DB }}
          DB_USER: ${{ secrets.DB_USER }}
          PASS: ${{ secrets.PASS }}
          HOST: ${{ secrets.HOST }}
          PORT: ${{ secrets.PORT }}
        run: |
          python db_to_json.py
          echo ${{ env.DO_COMMIT }}
      - name: Push to GitHub
        if: ${{ env.DO_COMMIT == 'true' }}
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git add .
          git commit -m "Update leaderboard"
          git push origin gh-pages
