name: lint

on:
  push:
  pull_request:
    types: [ opened, synchronize ]

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: psf/black@stable
  pyright:
    runs-on: ubuntu-latest
    steps:
      - name: Run pyright
        uses: jakebailey/pyright-action@v1
        with:
          warnings: false
          working-directory: ../
          lib: true
